import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

// Amplify configuration — wrapped in try/catch for local dev without sandbox
try {
  const { Amplify } = await import('aws-amplify')
  // @ts-ignore — amplify_outputs.json is generated by `npx ampx sandbox` or cloud deploy
  const outputs = await import('../amplify_outputs.json')
  Amplify.configure(outputs.default || outputs)
  console.log('[Amplify] Configured successfully')

  // Initialize the data client for cloud DB operations
  const { initAmplifyDataClient } = await import('./services/amplifyDataService')
  await initAmplifyDataClient()
} catch (e) {
  console.warn('[Amplify] amplify_outputs.json not found or Amplify not configured. Running in local-only mode.')
}
import { useAppStore, useAuthStore } from './stores'

window.addEventListener('error', (event) => {
  const user = useAuthStore.getState().user
  useAppStore.getState().logError({
    errorMessage: event.message,
    stackTrace: event.error?.stack || 'No stack trace',
    userId: user?.id,
    pageName: window.location.pathname,
    source: window.location.pathname.startsWith('/admin') ? 'dashboard' : 'tech-tasks',
  })
})

window.addEventListener('unhandledrejection', (event) => {
  const user = useAuthStore.getState().user
  useAppStore.getState().logError({
    errorMessage: event.reason?.message || String(event.reason),
    stackTrace: event.reason?.stack || 'No stack trace',
    userId: user?.id,
    pageName: window.location.pathname,
    source: window.location.pathname.startsWith('/admin') ? 'dashboard' : 'tech-tasks',
  })
})

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
